import { Capriola } from "next/font/google";
import "./globals.css";

const capriola = Capriola({
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${capriola.className} antialiased`}>{children}</body>
    </html>
  );
}
